apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: eucaim
data:
#        proxy_set_header X-Forwarded-Port $server_port;
#        proxy_set_header X-Forwarded-Host $server_name;
#        proxy_pass http://molgenis.eucaim.svc.cluster.local:8080;
  backend.conf: |-
     location / {
        resolver kube-dns.kube-system.svc.cluster.local;
        proxy_pass http://molgenis.ramses.i3m.upv.es;
        client_max_body_size 0;
        proxy_read_timeout 600s;
      }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconf
  namespace: eucaim
data:
#        proxy_set_header X-Forwarded-Port $server_port;
#        proxy_set_header X-Forwarded-Host $server_name;
#        proxy_pass http://molgenis.eucaim.svc.cluster.local:8080;
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
        client_max_body_size 5M;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        include /etc/nginx/conf.d/*.conf;
    }
